language: node_js
node_js:
- stable
branches:
  only:
  - master
deploy:
  edge: true
  skip_cleanup: true
  provider: npm
  email: at@webhouse.dk
  api_key:
    secure: jKdYe08TCqFSc/IwYxZCl25gseTLx81dHlDIijoU7t7HbFiDnupFSgVuyHZt9LXo4fP2wrjBvFvzM6JMy8agyRqZHWNYgiY/bamqauxgT+NUZGHGBqxO5cdfBaD/A2Ussnt9ezTYcGv82GIEbOhPk5ePuhPl4U2xqEMMbzYyakSjy1FEmB3hxd/CknkGPKUystdiaajmQlLbaKcoas/CGQsikMgGfA/YZAINpMq2WTxEaLTBqwuYSoiBEpBPm7kmtSBINic1GPelr3XKkeoAiuIkAqP90DvrzIZZqW9muOUhIvto65KCiTgJ48t8Q7In3t1kjaN+6LbIyQpQdHFvttS5WgYJYKQHvRGJ9l7Z9Lfj+GXBK9qsBcLORJksLPudvwoJUFBqAo5xuUVyM2sgLHQ0dA9HGScDN5AOCWoo4ChAXFayzFjHjzds//yF1nJMeeEZ5iHOylKGDAnS46KOtnAfOfLmdNBAV9/AhyeyIuFL9PAW2f1WIS4DLg6mnGpKWYIQF94F8Rh7fjhOpYGAPFt0PKHwKpkQkRSbZgrAIEP/KjGamFEr3QoGbLb2c29MLqnHLSZj/rQ8ki3axCEvvG0PMNKcn+3AMtVNLcDwQu5gGfP5jvG33wQIe7U4lBts9azLChtusXdCINuuYyoeCMrWYgzWO/n/ijj2WnQSKZ0=
  on:
    repo: senti-iot/senti-ml-model-water
notifications:
  email:
    recipients:
    - at@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: WkZ0yKXxtCpr+kMT7kEvS/wHgkyJvax919tce5HVSMxeVzDs+bSKnD+QoiXFupFWzSbW1yOAI1czKizej+V0pExFqpQ2q1KRwXMOgy42BS5MHQ0Pcx/yyG8hw/7oRWXVxxfNa6/jxiQ431xo3r0Z7rDYazpcLC/xHKJjKpJ63/lssJveFxuJpX8hPFAdHV2vrBxM8eaQDPUcXxGNnzcxUnCv25NwMd/6HlmtKLIBKWuc26ahfryeW9KV4zQJ9AohI/hKBNG8gSMMtAGlz04Dr9WdeeMlE1Fl5ZGlIjQzSZohA3kQbY84AomKQ8t+zLF2C3PS9ZL2vydvcVsHq55HZiwC8/Xtd0EVDJ8ZFkoGflTpUzjoAuv0t/A4cGqZiGd/lDWSWWjhyrYWblwyLhIQs1pQQLSnBM803SaxddEfCRiFW9yLvmf/W1SM58T4nfzcV8Bu0ngwNhMhWFPLETMJwO0JhiM4QcgU6f/AB1ZTvs6GBzpV+9a7ihDaFJFSWyzv9xT/jDhkLIVOBsMao7ZY9WdjeKaJ3u6XT6euV1lQwu09GcF8Tw4pshQEKCUEBPK8mptJUeKupansKkOIv5jp4/KOT6T0YTWP9jJISM8OTn6ZDAcIwHexUa+mrDyq13alvAtYc2izJhMmxjVRS60Jl2sbTe4A1T5rIkR2jlp1HUY=
